import Head from 'next/head'
import CommentModal from '../../components/CommentModal'
import Sidebar from '../../components/Sidebar'
import Widgets from '../../components/Widgets'

export default function Post({newsResults,randomUsersResults}) {
  return (
    <div>
      <Head>
        <title>Post page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto ">

        {/*Sidebar*/}
        <Sidebar/>


        {/*Widgets*/}
        <Widgets newsResults={newsResults.articles} randomUsersResults={randomUsersResults.results}/>

        {/*Modal*/}
        <CommentModal></CommentModal>

      </main>

    </div>
  )
}
//https://saurav.tech/NewsAPI/top-headlines/category/business/in.json

export async function getServerSideProps(){
  const newsResults = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/health/in.json").then((res)=>res.json());

  //Who to follow section
  const randomUsersResults = await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture").then((res)=>res.json());
  return{
    props:{
      newsResults,randomUsersResults
    }
  }
}
